cloud1: Cloud Border {
  shape: cloud
  style.stroke: cyan
  style.stroke-width: 4
  label.near: border-bottom-center
}

cloud2: Cloud Outside {
  shape: cloud
  style.stroke: green
  style.stroke-width: 4
  label.near: outside-bottom-center
}