classes: {
  NONE: {style.opacity: 0}
  GREEN: {style.stroke: "#2b9464"; style.fill: "#2b9464"}
  RED: {style.stroke: "#d14d28"; style.fill: "#d14d28"}
  YELLOW: {style.stroke: "#f5df65"; style.fill: "#f5df65"}
  BLUE: {style.stroke: "#59c8df"; style.fill: "#59c8df"}
}

grid-rows: 12
grid-columns: 12
grid-gap: 0

12-1: "" {class: NONE}
12-2: "" {class: NONE}
12-3: "" {class: NONE}
12-4: "" {class: NONE}
12-5: "" {class: NONE}
12-6: "" {class: NONE}
12-7: "" {class: NONE}
12-8: "" {class: NONE}
12-9: "" {class: NONE}
12-10: "" {class: NONE}
12-11: "" {class: GREEN}
12-12: "北海道" {class: GREEN}

11-1: "" {class: NONE}
11-2: "" {class: NONE}
11-3: "" {class: NONE}
11-4: "" {class: NONE}
11-5: "" {class: NONE}
11-6: "" {class: NONE}
11-7: "" {class: NONE}
11-8: "" {class: NONE}
11-9: "" {class: NONE}
11-10: "" {class: NONE}
11-11: "" {class: GREEN}
11-12: "" {class: GREEN}

10-1: "" {class: NONE}
10-2: "" {class: NONE}
10-3: "" {class: NONE}
10-4: "" {class: NONE}
10-5: "" {class: NONE}
10-6: "" {class: NONE}
10-7: "" {class: NONE}
10-8: "" {class: NONE}
10-9: "" {class: NONE}
10-10: "" {class: NONE}
10-11: "青森" {class: RED}
10-12: "" {class: NONE}

9-1: "" {class: NONE}
9-2: "" {class: NONE}
9-3: "" {class: NONE}
9-4: "" {class: NONE}
9-5: "" {class: NONE}
9-6: "" {class: NONE}
9-7: "" {class: NONE}
9-8: "" {class: NONE}
9-9: "" {class: NONE}
9-10: "" {class: NONE}
9-11: "秋田" {class: YELLOW}
9-12: "岩手" {class: GREEN}

8-1: "" {class: NONE}
8-2: "" {class: NONE}
8-3: "" {class: NONE}
8-4: "" {class: NONE}
8-5: "" {class: NONE}
8-6: "" {class: NONE}
8-7: "" {class: NONE}
8-8: "石川" {class: GREEN}
8-9: "" {class: NONE}
8-10: "新潟" {class: BLUE}
8-11: "山形" {class: RED}
8-12: "宮城" {class: BLUE}

7-1: "" {class: NONE}
7-2: "" {class: NONE}
7-3: "" {class: NONE}
7-4: "" {class: NONE}
7-5: "" {class: NONE}
7-6: "" {class: NONE}
7-7: "" {class: NONE}
7-8: "福井" {class: RED}
7-9: "富山" {class: YELLOW}
7-10: "群馬" {class: GREEN}
7-11: "栃木" {class: YELLOW}
7-12: "福島" {class: GREEN}

6-1: "" {class: NONE}
6-2: "" {class: NONE}
6-3: "山口" {class: RED}
6-4: "島根" {class: YELLOW}
6-5: "鳥取" {class: RED}
6-6: "兵庫" {class: BLUE}
6-7: "京都" {class: YELLOW}
6-8: "滋賀" {class: GREEN}
6-9: "長野" {class: RED}
6-10: "山梨" {class: YELLOW}
6-11: "埼玉" {class: BLUE}
6-12: "茨城" {class: RED}

5-1: "" {class: NONE}
5-2: "" {class: NONE}
5-3: "" {class: NONE}
5-4: "広島" {class: BLUE}
5-5: "岡山" {class: YELLOW}
5-6: "大阪" {class: GREEN}
5-7: "奈良" {class: RED}
5-8: "岐阜" {class: BLUE}
5-9: "愛知" {class: YELLOW}
5-10: "静岡" {class: BLUE}
5-11: "TOKYO" {class: GREEN}
5-12: "千葉" {class: YELLOW}

4-1: "長崎" {class: BLUE}
4-2: "佐賀" {class: RED}
4-3: "福岡" {class: GREEN}
4-4: "" {class: NONE}
4-5: "" {class: NONE}
4-6: "" {class: NONE}
4-7: "和歌山" {class: GREEN}
4-8: "三重" {class: RED}
4-9: "" {class: NONE}
4-10: "" {class: NONE}
4-11: "神奈川" {class: RED}
4-12: "" {class: NONE}

3-1: "" {class: NONE}
3-2: "熊本" {class: YELLOW}
3-3: "大分" {class: BLUE}
3-4: "" {class: NONE}
3-5: "愛媛" {class: RED}
3-6: "香川" {class: BLUE}
3-7: "" {class: NONE}
3-8: "" {class: NONE}
3-9: "" {class: NONE}
3-10: "" {class: NONE}
3-11: "" {class: NONE}
3-12: "" {class: NONE}

2-1: "" {class: NONE}
2-2: "鹿児島" {class: RED}
2-3: "宮崎" {class: GREEN}
2-4: "" {class: NONE}
2-5: "高知" {class: GREEN}
2-6: "徳島" {class: YELLOW}
2-7: "" {class: NONE}
2-8: "" {class: NONE}
2-9: "" {class: NONE}
2-10: "" {class: NONE}
2-11: "" {class: NONE}
2-12: "" {class: NONE}

1-1: "沖縄" {class: BLUE}
1-2: "" {class: NONE}
1-3: "" {class: NONE}
1-4: "" {class: NONE}
1-5: "" {class: NONE}
1-6: "" {class: NONE}
1-7: "" {class: NONE}
1-8: "" {class: NONE}
1-9: "" {class: NONE}
1-10: "" {class: NONE}
1-11: "" {class: NONE}
1-12: "" {class: NONE}
